SELECT ANIMAL_ID, NAME
FROM (SELECT ANIMAL_ID, I.NAME, (O.DATETIME - I.DATETIME) T
      FROM ANIMAL_OUTS O JOIN ANIMAL_INS I
                              USING(ANIMAL_ID)
      ORDER BY T DESC) S
LIMIT 2;