SELECT D1.ID, D1.GENOTYPE as GENOTYPE, D2.GENOTYPE as PARENT_GENOTYPE
FROM ECOLI_DATA D1
         JOIN ECOLI_DATA D2
              ON D1.PARENT_ID = D2.ID
WHERE D1.GENOTYPE & D2.GENOTYPE = D2.GENOTYPE
ORDER BY ID