SELECT YEAR(E.DIFFERENTIATION_DATE) YEAR, J.MAXSIZE - E.SIZE_OF_COLONY YEAR_DEV, E.ID
FROM ECOLI_DATA E join (SELECT YEAR(DIFFERENTIATION_DATE) as je, MAX(SIZE_OF_COLONY) as MAXSIZE
                        FROM ECOLI_DATA
                        GROUP BY YEAR(DIFFERENTIATION_DATE)) J
                       ON YEAR(DIFFERENTIATION_DATE) = je
ORDER BY 1, 2;