SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(O.AMOUNT) * P.PRICE TOTAL_SALES
FROM FOOD_PRODUCT P
         JOIN
     FOOD_ORDER O
     USING(PRODUCT_ID)
WHERE O.PRODUCE_DATE LIKE "2022-05%"
GROUP BY P.PRODUCT_ID
ORDER BY 3 DESC, 1