SELECT CATEGORY, PRICE MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT P1
WHERE PRICE = (SELECT MAX(PRICE)
               FROM FOOD_PRODUCT P2
               WHERE P2.CATEGORY = P1.CATEGORY)
  AND
        CATEGORY IN ("과자", "국", "김치", "식용유")
ORDER BY 2 DESC