WITH RECURSIVE CTE AS(
    SELECT 0 AS NUM
    UNION ALL
    SELECT NUM +1
    FROM CTE
    WHERE NUM < 23)

SELECT CTE.NUM HOUR, COUNT(HOUR(O.DATETIME)) COUNT
FROM ANIMAL_OUTS O right Join CTE
                              ON HOUR(O.DATETIME) = CTE.NUM
GROUP BY 1
ORDER BY 1;