SELECT H.CAR_ID, IFNULL(A.AVAILABILITY,"대여 가능") AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H LEFT JOIN
     (SELECT CAR_ID, "대여중" AVAILABILITY
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE "2022-10-16" BETWEEN START_DATE AND END_DATE
      GROUP BY 1
     ) A
     ON H.CAR_ID = A.CAR_ID
GROUP BY 1
ORDER BY 1 DESC
